version: '3'
services:
    redis:
      container_name: redis
      restart: always
      image: redislabs/redisgraph
      privileged: true
      ports:
        - "6379:6379"
      volumes:
        - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
        - ./data:/data
        - ./logs:/logs
      sysctls:
        - net.core.somaxconn=65535
      command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--loadmodule" ,"/usr/lib/redis/modules/redisgraph.so"]
